In [1]:
import torch
import numpy as np

### 텐서 초기화

In [13]:
data=[[1,2],[3,4]]
np_array=np.array(data)
x_np=torch.from_numpy(np_array) # 넘파이에서 텐서로 변환
x=torch.tensor(data) # 데이터에서 직접 텐서로 변환
x_ones=torch.ones_like(x) # 텐서를 다 1로 변환
x_rand=torch.rand_like(x,dtype=float) # 텐서를 다 0~1 사이의 랜덤 난수로 변환
print(np_array)
print(x_np)
print(x)
print(x_ones)
print(x_rand)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.7261, 0.0053],
        [0.5790, 0.9768]], dtype=torch.float64)


In [11]:
shape=(2,3,)
rand_tensor=torch.rand(shape) # 지정한 차원의 랜덤 텐서 
ones_tensor = torch.ones(shape) # 지정한 차원의 1로 채워진 텐서
zeros_tensor=torch.zeros(shape) # 지정한 차원의 0으로 채워진 텐서
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8362, 0.5184, 0.7068],
        [0.5746, 0.5326, 0.9361]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서의 속성

In [16]:
tensor=torch.rand(3,4)
print(tensor.shape) # 텐서의 차원
print(tensor.dtype) # 텐서의 타입
print(tensor.device) # 텐서의 디바이스

torch.Size([3, 4])
torch.float32
cpu


### 텐서 연산

In [21]:
if torch.cuda.is_available():
    tensor=tensor.to('cuda') # GPU가 있다면 텐서를 GPU로 연산
   
tensor=torch.ones(4,4)
print(tensor[0]) # 텐서의 첫째 행
print(tensor[:,0]) # 텐서의 첫째열
print(tensor[...,-1]) # 텐서의 마지막 열
tensor[:,1]=0 # 텐서의 두번쨰열 0으로 치환
print(tensor) 
    

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [22]:
t1=torch.cat([tensor,tensor,tensor],dim=1) # 가로방향으로 병합
t2=torch.cat([tensor,tensor,tensor],dim=0) # 세로방향으로 병합
print(t1)
print(t2)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
# 행렬곱 연산(y1=y2=y3)
y1= tensor @ tensor.T
y2= tensor.matmul(tensor.T)
y3= torch.rand_like(y1)
torch.matmul(tensor,tensor.T, out=y3)
print(y1)
print(y2)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [29]:
# 요소별 곱(z1=z2=z3)
z1=tensor*tensor
z2=tensor.mul(tensor)
z3=torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z1)
print(z2)
print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [36]:
agg=tensor.sum() # 텐서안의 모든 값의 총합을 텐서로 출력
agg_item=agg.item() # 텐서에서 숫자값으로 변환
print(agg)
print(agg_item, type(agg_item))
tensor.add_(5)  # 텐서의 모든원소에 5씩 더함
print(tensor) 

tensor(12.)
12.0 <class 'float'>
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Numpy 변환(Bridge)

In [42]:
t= torch.ones(5) # 차원5인 1로 채워진 텐서
print(t)
n=t.numpy() # 텐서를 넘파이로 변환
print(n)
t.add_(1) # 텐서의 모든 원소에 1씩 더함
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [44]:
n=np.ones(5) # 차원 5인 1로 채워진 넘파이 생성
print(n)
t=torch.from_numpy(n) # 넘파이 텐서로 변환
print(t)
np.add(n,1,out=n) # 넘파이의 모든 원소에 1씩 더함
print(n)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
